
# Site settings
title: Simcookies
email: songan840136@gmail.com
description: All about Simcookies Project.
baseurl: "" # the subpath of site
url: "https://simcookies.github.io" # the base hostname & protocol for site
exclude: ["Gemfile", "Gemfile.lock", "Rakefile",
          "gulpfile.js", "node_modules", "package-lock.json",
          "package.json", "vendor/"]

# default setting
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true


# Social info
twitter_username:  Simcookies
github_username:   simcookies

# Build settings
keep: [".git", ".nojekyll", ".htaccess"]
gems:
  - jekyll-toc
  - jekyll-paginate
  - jemoji

permalink: /:year/:month/:day/:title
paginate: 8
paginate_path: "page:num"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
