# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simcookies Blog
email: mssongan840136@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  All about Simcookies Project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simcookies.github.io" # the base hostname & protocol for your site
twitter_username:  moshui804
github_username:   Simcookies
facebook_username: flame804

# Build settings
markdown: kramdown

destination: ../site