
# Site settings
title: Simcookies
email: songan840136@gmail.com
description: All about Simcookies Project.
baseurl: "" # the subpath of site
url: "http://simcookies.github.io" # the base hostname & protocol for site
exclude: ["Gemfile", "Gemfile.lock", "Rakefile"]

# default setting
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Social info
twitter_username:  Simcookies
github_username:   Simcookies

# Build settings
gems: [jekyll-paginate]
destination: ../site
permalink: /:year/:month/:day/:title
paginate: 15
paginate_path: "page:num"

# Markdown settings
markdown: redcarpet
redcarpet:
  extensions:
      - fenced_code_blocks
      - no_intra_emphasis
      - strikethrough
      - autolink
      - tables