
# Site settings
title: Simcookies
email: mssongan840136@outlook.com
description: All about Simcookies Project.
baseurl: "" # the subpath of site
url: "http://simcookies.github.io" # the base hostname & protocol for site

# Social info
twitter_username:  moshui804
github_username:   Simcookies
facebook_username: flame804

# Build settings
destination: ../site
permalink: /:year/:month/:day/:title

# Markdown settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
      - fenced_code_blocks
      - no_intra_emphasis
      - strikethrough
      - autolink
      - tables